spring:
  application:
    name: SpringAppSupportsSocialLogin

  security:
    user:
      name: kprahul
      password: kprahul143


logging:
  level:
    org.springframework.security: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

server:
  port: 8090

github:
  client-id: '*****************'
  client-secret: '****************************'

#spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liCBLLUjii41pS7k}
#spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:9da8734b56aad52d91b268fe6834a8df12447d95}

#spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:974042741122392}
#spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:36d48c25c1767d58b3101551513d7e1e}